# Generated by Django 4.1.4 on 2023-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/post_photos'),
        ),
    ]
