# Generated by Django 4.1.4 on 2023-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0015_grocery_list_alter_userprofile_role_categorystorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_list',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
