# Generated by Django 4.1.4 on 2023-01-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0021_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_list',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_list_category', to='socialPage.items'),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='storage_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_list_storage', to='socialPage.items'),
        ),
    ]
