# Generated by Django 4.1.4 on 2023-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0024_rename_grocery_list_singleitem_grocerylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='item_name',
            field=models.ManyToManyField(blank=True, related_name='items_name', to='socialPage.singleitem'),
        ),
    ]
