# Generated by Django 4.1.4 on 2023-01-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0028_alter_grocerylist_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='item_name',
            field=models.ManyToManyField(blank=True, related_name='item_name', to='socialPage.singleitem'),
        ),
    ]
