# Generated by Django 4.1.4 on 2023-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0029_rename_item_name_singleitem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='item_name',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(blank=True, default='grocery list', max_length=255, null=True),
        ),
    ]
