# Generated by Django 4.1.4 on 2023-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0030_rename_name_singleitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='grocery_items',
            field=models.ManyToManyField(blank=True, related_name='grocery_items', to='socialPage.singleitem'),
        ),
    ]
