# Generated by Django 4.1.4 on 2023-01-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0034_alter_grocerylist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='owner',
        ),
    ]
