# Generated by Django 4.1.4 on 2023-01-24 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialPage', '0035_remove_grocerylist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(blank=True, default='grocery list', max_length=30, null=True),
        ),
    ]
