# Generated by Django 4.1.4 on 2023-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0037_rename_user_grocerylist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='user_id',
        ),
    ]
