# Generated by Django 4.1.4 on 2023-01-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialPage', '0040_alter_singleitem_food_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='grocery_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='grocery_items', to='socialPage.singleitem'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='list_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
