# Generated by Django 4.1.4 on 2023-02-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPage', '0042_alter_grocerylist_grocery_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Restaurateur', 'restaurateur'), ('Amateur chef', 'amateur chef')], max_length=30, null=True),
        ),
    ]
